apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dog0bjafa-nodejs
  janus-idp.io/tekton: dog0bjafa-nodejs
  backstage.io/kubernetes-id: dog0bjafa-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dog0bjafa-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
